[package]
name = "entr"
version = "0.1.0"
authors = ["Mauri de Souza Nunes <mauri870@gmail.com>"]
edition = "2018"

[dependencies]
notify = "4.0.0"
failure = "0.1.4"
exitfailure = "0.5.1"
structopt = "0.2.14"
